# Generated by Django 3.2.7 on 2021-11-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
        ('CART', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default='')),
                ('no_of_services', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=80)),
                ('ordered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
